com.dataqualityworks.rdfbuilder:
    reader:
        csv:
            - name: specifications/actions.csv
            - name: specifications/business-units.csv
            - name: specifications/containers-source.csv
            - name: specifications/containers-target.csv
            - name: specifications/mappings.csv
            - name: specifications/people.csv
    writer: 
        ttl:
            name: graph.ttl
    namespaces:
        - prefix: dqwdg
          uri: https://dataqualityworks.com/terms/data-governance/
        - prefix: ex-bu
          uri: https://example.com/business-units/
        - prefix: ex-cont
          uri: https://example.com/data-containers/
        - prefix: ex-mapping
          uri: https://example.com/mappings/
        - prefix: ex-ppl
          uri: https://example.com/people/
